project_id = "ckcqttsdpxfbpkzljctl"

[functions.generate-gift-suggestions]
verify_jwt = false

[functions.get-amazon-products]
verify_jwt = false

[functions.get-amazon-associate-id]
verify_jwt = false