project_id = "ckcqttsdpxfbpkzljctl"

[api]
enabled = true

[functions]
[functions.generate-gift-suggestions]
verify_jwt = false

[functions.get-amazon-products]
verify_jwt = false

[functions.get-amazon-associate-id]
verify_jwt = false