export const AMAZON_CONFIG = {
  MAX_CONCURRENT_REQUESTS: 4, // Reduced from 8
  STAGGER_DELAY: 100, // Increased from 50
  MAX_RETRIES: 3,
  BASE_RETRY_DELAY: 1000,
  MAX_BACKOFF_DELAY: 5000, // Increased from 3000
  BACKOFF_FACTOR: 2
};