export const AMAZON_CONFIG = {
  MAX_CONCURRENT_REQUESTS: 8, // Increased from 3 to 8
  STAGGER_DELAY: 100, // Reduced from 1000ms to 100ms
  MAX_RETRIES: 1,
  BASE_RETRY_DELAY: 25,
  MAX_BACKOFF_DELAY: 100,
  BACKOFF_FACTOR: 1.01
};