export const AMAZON_CONFIG = {
  MAX_CONCURRENT_REQUESTS: 4, // Reduced from 8
  BASE_RETRY_DELAY: 1000,
  MAX_RETRY_ATTEMPTS: 3,
  BACKOFF_FACTOR: 2,
  MAX_BACKOFF_DELAY: 10000,
  STAGGER_DELAY: 250,
  BATCH_SIZE: 4, // Reduced from 8
  REQUEST_TIMEOUT: 8000
} as const;